#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nginx

# roles/hello/tasks/main.yml
- name: Say hello
  ansible.builtin.debug:
    msg: "Hello from padminisys.hello! user={{ hello_user | default('world') }}"
