---
# Ansible Collection Requirements for AWX/AAP Execution Environment
collections:
  - name: kubernetes.core
    version: ">=2.4.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=7.0.0"
