# SPDX-License-Identifier: MIT-0
---
# defaults file for roles/nginx

# Nginx Ingress Controller Configuration
nginx_ingress:
  # Helm chart configuration
  chart_name: "ingress-nginx"
  chart_repo: "https://kubernetes.github.io/ingress-nginx"
  release_name: "ingress-nginx"
  namespace: "ingress-nginx"
  create_namespace: true

  # Kubeconfig handling
  # If not specified, will use default location (~/.kube/config)
  kubeconfig_path: ""

  # Values file path (relative to role templates directory)
  values_file: "values.yaml"

  # Service configuration
  service:
    type: "NodePort"

  # Additional helm options
  helm:
    wait: true
    timeout: "10m"
    force: false
