---
# AWX/AAP Execution Environment Definition
# This file defines the execution environment for running this collection in AWX/AAP

version: 3

images:
  base_image:
    name: 'quay.io/ansible/awx-ee:latest'

dependencies:
  galaxy: requirements-awx.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend_base:
    - RUN whoami
    - RUN cat /etc/os-release
  prepend_galaxy:
    - RUN echo "Setting up Galaxy configuration for better reliability"
    - RUN mkdir -p ~/.ansible
    - RUN echo "[defaults]" > ~/.ansible/ansible.cfg
    - RUN echo "host_key_checking = False" >> ~/.ansible/ansible.cfg
    - RUN echo "[galaxy]" >> ~/.ansible/ansible.cfg
    - RUN echo "server_list = release_galaxy" >> ~/.ansible/ansible.cfg
    - RUN echo "[galaxy_server.release_galaxy]" >> ~/.ansible/ansible.cfg
    - RUN echo "url = https://galaxy.ansible.com/" >> ~/.ansible/ansible.cfg
  prepend_final:
    - RUN ansible-galaxy collection list || echo "No collections installed yet"

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--timeout=60 --retries=3"
