---
# Simplified AWX/AAP Execution Environment Definition
# This is a more reliable version for CI/CD builds

version: 3

images:
  base_image:
    name: 'quay.io/ansible/awx-ee:24.6.1'

dependencies:
  galaxy: requirements-build.yml
  python: requirements.txt
  system: bindep.txt

build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "--timeout=60 --retries=3"